wac/Controllers/AccessController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using wac.Interfaces.Providers;
using wac.Models.Access;
using wac.Types;

namespace wac.Controllers
{
    public class AccessController : Controller
    {
        private readonly ISettingsProvider _settingsProvider;
        private readonly Settings _settings;
        private readonly Interfaces.Handlers.Access.IAuthenticationHandler _authenticationHandler;
        private readonly ILogProvider _logProvider;

        public AccessController(ISettingsProvider settingsProvider, Interfaces.Handlers.Access.IAuthenticationHandler authenticationHandler, ILogProvider logProvider)
        {
            _settingsProvider = settingsProvider;
            _settings = settingsProvider.Get();
            _authenticationHandler = authenticationHandler;
            _logProvider = logProvider;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel viewModel)
        {
            _authenticationHandler.RequestAuthentication(viewModel.LoginRequest);
                
            return View("EmailSent");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(scheme: _settings.Authorisation.Scheme);
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Authenticate(string token)
        {
            User user;
            if (_authenticationHandler.ValidateToken(token, out user))
            {
                HttpContext.Session.SetString("FirstName", user.FirstName);

                List<Claim> roleClaims = user.Roles.ConvertAll(x => new Claim(ClaimTypes.Role, x.Name));

                List<Claim> claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, token),
                };
                claims.AddRange(roleClaims);

                ClaimsIdentity identity = new ClaimsIdentity(claims, "cookie");
                ClaimsPrincipal principal = new ClaimsPrincipal(identity);
                
                await HttpContext.SignInAsync(
                        scheme: _settings.Authorisation.Scheme,
                        principal: principal);

                return RedirectToAction("Index", "Home");
            }

            return View("Custom401");
        }
    }
}

wac/Controllers/ContentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using wac.Interfaces.Handlers.Content;
using wac.Models.Content;
using wac.Types.Constants;
using wac.Interfaces.Providers;
using Microsoft.AspNetCore.Authorization;

namespace wac.Controllers
{
    public class ContentController : Controller
    {
        private readonly IContentHandler _contentHandler;
        private readonly IClubProvider _clubProvider;
        private readonly ILogProvider _logProvider;

        public ContentController(IContentHandler contentHandler, IClubProvider clubProvider, ILogProvider logProvider)
        {
            _contentHandler = contentHandler;
            _clubProvider = clubProvider;
            _logProvider = logProvider;
        }

        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        public IActionResult Edit(int id)
        {
            var vm = new EditContentViewModel {
                Content = _contentHandler.GetContent(id)
            };
            vm.Content.ClubAreas = _clubProvider.GetClubAreas();
            return View(vm);
        }

        [HttpGet]
        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        public IActionResult Create()
        {
            var vm = new CreateContentViewModel {
                Content = new Types.Content
                {
                    Title = "New content",
                    PublishDateTime = DateTime.Now,
                    ClubArea = new Types.ClubArea { Id = 0 },
                    ClubAreas = _clubProvider.GetClubAreas(),
                    IsNew = true
                }
            };

            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Types.Content content)
        {
            var vm = new EditContentViewModel();

            vm.Content = _contentHandler.CreateContent(content);
            vm.Content.IsNew = false;
            vm.Content.ClubAreas = _clubProvider.GetClubAreas();
            vm.FlashMessage = new Types.FlashMessage { Message = string.Format(FlashMessages.CONTENT_CREATE_SUCCESSFUL, content.Title), State = Types.FlashMessageState.Successful, CssClass = FlashMessageCssClasses.CONTENT_CREATE_SUCCESSFUL };
            
            return View("Edit", vm);
        }

        [HttpPost]
        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        [ValidateAntiForgeryToken]
        public IActionResult Save(Types.Content content)
        {
            var vm = new EditContentViewModel { Content = content };

            if (_contentHandler.UpdateContent(content))
            {
                vm.Content.ClubAreas = _clubProvider.GetClubAreas();
                vm.Content.IsNew = false;
                vm.FlashMessage = new Types.FlashMessage { Message = string.Format(FlashMessages.CONTENT_EDIT_SUCCESSFUL, content.Title), State = Types.FlashMessageState.Successful, CssClass = FlashMessageCssClasses.CONTENT_EDIT_SUCCESSFUL };
                return View("Edit", vm);
            }

            vm.Content.ClubAreas = _clubProvider.GetClubAreas();
            vm.Content.IsNew = false;
            vm.FlashMessage = new Types.FlashMessage { Message = string.Format(FlashMessages.CONTENT_EDIT_FAILED, content.Title), State = Types.FlashMessageState.Failed, CssClass = FlashMessageCssClasses.CONTENT_EDIT_FAILED };
            return View("Edit", vm);
        }

        public IActionResult Index(int clubAreaId)
        {
            var vm = new ContentViewModel();
            var canAdministerContent = _contentHandler.HasContentAdministratorRole();

            vm.PagedNews = _contentHandler.FetchContentForClubArea(clubAreaId, DateTime.MaxValue, !canAdministerContent, false);
            vm.ClubAreas = _contentHandler.GetClubAreas();
            vm.CurrentClubArea =  clubAreaId == 0 ? new Types.ClubArea { Id = 0, Description = "All Weston AC news", Name = "All news" }  : vm.ClubAreas.Find(x => x.Id == clubAreaId);
            vm.ClubAreaId = clubAreaId;
            vm.OldestNewsDateTime = vm.PagedNews.Count > 0 ? vm.PagedNews.OrderBy(x => x.PublishDateTime).FirstOrDefault().PublishDateTime : DateTime.Now;
            vm.CanAdministerContent = canAdministerContent;
            
            return View(vm);
        }
    }
}

wac/Controllers/MessageBoardsController.cs
using Microsoft.AspNetCore.Mvc;
using wac.Models.Messages;
using wac.Interfaces.Handlers.Messages;
using Microsoft.AspNetCore.Authorization;

namespace wac.Controllers
{
    [Authorize]
    public class MessageBoardsController : Controller
    {
        private readonly IMessagesHandler _messagesHandler;

        public MessageBoardsController(IMessagesHandler messagesHandler)
        {
            _messagesHandler = messagesHandler;
        }

        public IActionResult Index()
        {
            var vm = new GetAllMessageBoardsViewModel();
            vm.MessageBoards = _messagesHandler.GetAllMessageBoards();

            return View(vm);
        }
    }
}

wac/Controllers/SocialDiaryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using wac.Interfaces.Handlers.Events;
using wac.Interfaces.Providers;
using wac.Models.Events;
using wac.Types;
using wac.Types.Constants;

namespace wac.Controllers
{
    public class SocialDiaryController : Controller
    {
        private readonly ISocialDiaryHandler _socialDiaryHandler;
        private readonly IDateTimeProvider _dateTimeProvider;

        public SocialDiaryController(ISocialDiaryHandler socialDiaryHandler, IDateTimeProvider dateTimeProvider)
        {
            _socialDiaryHandler = socialDiaryHandler;
            _dateTimeProvider = dateTimeProvider;
        }

        public IActionResult Index()
        {
            var vm = new SocialDiaryViewModel();
            vm.CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole();
            vm.SocialEvents = _socialDiaryHandler.FetchSocialDiaryForClubArea(1, false);

            return View(vm);
        }

        public IActionResult View(int id)
        {
            var vm = new SocialEventViewModel();
            vm.CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole();
            vm.SocialEvent = _socialDiaryHandler.GetSocialEvent(id);

            return View(vm);
        }

        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        public IActionResult Create()
        {
            var vm = new SocialEventViewModel();
            vm.CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole();
            vm.SocialEvent = new SocialEvent { EventDate = _dateTimeProvider.GetUtcNow(), IsNew = true };

            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles = Roles.SOCIAL_DIARY_ADMINISTRATOR)]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SocialEvent socialEvent)
        {
            var vm = new SocialEventViewModel();
            vm.CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole();
            vm.SocialEvent = _socialDiaryHandler.CreateSocialEvent(socialEvent);
            vm.FlashMessage = new FlashMessage { Message = string.Format(FlashMessages.SOCIALDIARY_SAVE_SUCCESSFUL), State = FlashMessageState.Successful, CssClass = FlashMessageCssClasses.SOCIALDIARY_SAVE_SUCCESSFUL };

            return View("Edit", vm);
        }

        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        public IActionResult Edit(int id)
        {
            var vm = new SocialEventViewModel
            {
                CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole(),
                SocialEvent = _socialDiaryHandler.GetSocialEvent(id)
            };

            vm.SocialEvent.IsNew = false;

            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles = Roles.SOCIAL_DIARY_ADMINISTRATOR)]
        [ValidateAntiForgeryToken]
        public IActionResult Save(SocialEvent socialEvent)
        {
            var vm = new SocialEventViewModel
            {
                SocialEvent = socialEvent,
                CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole(),
            };

            vm.SocialEvent.ClubArea = new ClubArea { Id = 1 };

            if (_socialDiaryHandler.UpdateSocialEvent(socialEvent))
            {
                vm.SocialEvent.IsNew = false;
                vm.FlashMessage = new FlashMessage { Message = string.Format(FlashMessages.SOCIALDIARY_SAVE_SUCCESSFUL), State = FlashMessageState.Successful, CssClass = FlashMessageCssClasses.SOCIALDIARY_SAVE_SUCCESSFUL };
                return View("Edit", vm);
            }

            vm.SocialEvent.IsNew = false;
            vm.FlashMessage = new FlashMessage { Message = string.Format(FlashMessages.SOCIALDIARY_SAVE_FAILED), State = FlashMessageState.Failed, CssClass = FlashMessageCssClasses.SOCIALDIARY_SAVE_FAILED };
            return View("Edit", vm);
        }

        [HttpPost]
        [Authorize(Roles = Roles.SOCIAL_DIARY_ADMINISTRATOR)]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteEvent(SocialEventViewModel socialEventVm)
        {
            _socialDiaryHandler.DeleteEvent(socialEventVm.SocialEvent.Id);

            var vm = new SocialDiaryViewModel();
            vm.CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole();
            vm.SocialEvents = _socialDiaryHandler.FetchSocialDiaryForClubArea(1, false);

            return View("Index", vm);
        }
    }
}

wac/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Weston Athletic Club</title>

    @using Microsoft.AspNetCore.Http;
    @inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    <div id="page">
        <header>
            @*<a class="logo" title="Weston Athletic Club" href="http://www.westonac.co.uk">
                    <span>Weston Athletic Club</span>
                </a>*@
            <div class="hero">
                <h1>Road and trail running in Weston-super-Mare</h1>
            </div>
        </header>
        <nav>
            <ul>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index" title="Welcome" aria-haspopup="true">Welcome</a>
                    <ul>
                        <li>
                            <a title="News" asp-controller="Content" asp-action="Index">News</a>
                        </li>
                        <li>
                            <a title="Gallery" href="#">Gallery</a>
                        </li>
                        <li>
                            <a title="History" href="#">History</a>
                        </li>
                        <li>
                            <a title="Membership" href="#">Membership</a>
                        </li>
                        <li>
                            <a title="Coaching" href="#">Coaching</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a title="Races" href="#" aria-haspopup="true">Races</a>
                    <ul>
                        <li>
                            <a title="5k Handicap" href="~/StaticPage/Races/handicap">5k Handicap</a>
                        </li>
                        <li>
                            <a title="Weston Prom Run" href="~/StaticPage/Races/promraces">Weston Prom Run</a>
                        </li>
                        <li>
                            <a title="Beacon Batch" href="~/StaticPage/Races/beaconbatch">Beacon Batch</a>
                        </li>
                        <li>
                            <a title="Mendip Muddle" href="~/StaticPage/Races/muddle">Mendip Muddle</a>
                        </li>
                        <li>
                            <a title="Christmas Cracker 10k" href="~/StaticPage/Races/cracker">Christmas Cracker 10k</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a title="Members" href="#" aria-haspopup="true">Members</a>
                    <ul>
                        <li>
                            <a asp-area="" asp-controller="MessageBoards" asp-action="Index">Messages</a>
                        </li>
                        <li>
                            <a title="Club Championship" href="#" aria-haspopup="true" class="nav_ul_li_a_width200">Club Championship</a>
                            <ul>
                                <li>
                                    <a title="Results" href="#" aria-haspopup="true">Results</a>
                                    <ul>
                                        <li>
                                            <a title="Championship Races" href="#" class="nav_ul_li_a_width200">Championship Races</a>
                                        </li>
                                        <li>
                                            <a title="Other Races" href="#">Other Races</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a title="Triathlon" href="#">Triathlon</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a title="Personal Best" href="#">Personal Best</a>
                        </li>
                        <li>
                            <a title="My Results" href="#">My Results</a>
                        </li>
                        <li>
                            <a asp-action="index" asp-controller="SocialDiary" title="Social Events">Social Events</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Contact" title="Contact Us">Contact Us</a>
                </li>
                @{ var firstName = @HttpContextAccessor.HttpContext.Session.GetString("FirstName"); }
                @if (string.IsNullOrEmpty(firstName))
                {
                    <li><a asp-area="" asp-controller="Access" asp-action="Login">Login</a></li>
                }
                else
                {
                    <li><a asp-area="" asp-controller="Access" asp-action="Logout">@firstName - Logout</a></li>
                }
            </ul>

        </nav>
        <div class="container body-content">
            <hr />
            @RenderBody()
            <hr />

            <footer>
                <p>&copy; 2019 - Weston Athletic Club</p>
            </footer>
        </div>
    </div>
    @await Html.PartialAsync("~/Views/Partials/_cookieConsentPartialView.cshtml")
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    @RenderSection("Scripts", required: false)
</body>
</html>