wac/Models/Content/NewsGridViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace wac.Models.Content
{
    public class NewsGridViewModel
    {
        public List<News> NewsList { get; set; }

        public class News
        {
            public string Title { get; set; }
            public string Body { get; set; }
            public DateTime PublishedDateTime { get; set; }
        }
    }


}

wac/Models/Events/SocialDiaryViewModel.cs
using System.Collections.Generic;
using wac.Types;

namespace wac.Models.Events
{
    public class SocialDiaryViewModel
    {
        public List<SocialEvent> SocialEvents { get; set; }
        public bool CanAdministerSocialDiary { get; set; }
        public ClubArea CurrentClubArea { get; set; }
        public FlashMessage FlashMessage { get; set; }
        public List<ClubArea> ClubAreas { get; set; }
    }
}

wac/Models/Events/TrainingDiaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using wac.Types;
using wac.Types.Constants;

namespace wac.Models.Events
{
    public class TrainingDiaryViewModel
    {
        public List<wac.Types.Event> events { get; set; }
        public DateTime WeekCommencing { get; set; }
        public string WeekCommencingFormatted => WeekCommencing.ToString(Constants.CLIENTSIDE_DATETIME_FORMAT);
        public string WeekCommencingText => WeekCommencing.ToString("dddd, d MMMM yyyy");
        public bool CanAdministerTrainingDiary { get; set; }
        public ClubArea CurrentClubArea { get; set; }
        public FlashMessage FlashMessage { get; set; }
        public List<ClubArea> ClubAreas { get; set; }
    }
}

wac/Controllers/ContentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using wac.Interfaces.Handlers.Content;
using wac.Models.Content;
using wac.Types.Constants;
using wac.Interfaces.Providers;
using Microsoft.AspNetCore.Authorization;

namespace wac.Controllers
{
    public class ContentController : Controller
    {
        private readonly IContentHandler _contentHandler;
        private readonly IClubProvider _clubProvider;
        private readonly ILogProvider _logProvider;

        public ContentController(IContentHandler contentHandler, IClubProvider clubProvider, ILogProvider logProvider)
        {
            _contentHandler = contentHandler;
            _clubProvider = clubProvider;
            _logProvider = logProvider;
        }

        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        public IActionResult Edit(int id)
        {
            var vm = new EditContentViewModel {
                Content = _contentHandler.GetContent(id)
            };
            vm.Content.ClubAreas = _clubProvider.GetClubAreas();
            return View(vm);
        }

        [HttpGet]
        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        public IActionResult Create()
        {
            var vm = new CreateContentViewModel {
                Content = new Types.Content
                {
                    Title = "New content",
                    PublishDateTime = DateTime.Now,
                    ClubArea = new Types.ClubArea { Id = 0 },
                    ClubAreas = _clubProvider.GetClubAreas(),
                    IsNew = true
                }
            };

            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Types.Content content)
        {
            var vm = new EditContentViewModel();

            vm.Content = _contentHandler.CreateContent(content);
            vm.Content.IsNew = false;
            vm.Content.ClubAreas = _clubProvider.GetClubAreas();
            vm.FlashMessage = new Types.FlashMessage { Message = string.Format(FlashMessages.CONTENT_CREATE_SUCCESSFUL, content.Title), State = Types.FlashMessageState.Successful, CssClass = FlashMessageCssClasses.CONTENT_CREATE_SUCCESSFUL };
            
            return View("Edit", vm);
        }

        [HttpPost]
        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        [ValidateAntiForgeryToken]
        public IActionResult Save(Types.Content content)
        {
            var vm = new EditContentViewModel { Content = content };

            if (_contentHandler.UpdateContent(content))
            {
                vm.Content.ClubAreas = _clubProvider.GetClubAreas();
                vm.Content.IsNew = false;
                vm.FlashMessage = new Types.FlashMessage { Message = string.Format(FlashMessages.CONTENT_EDIT_SUCCESSFUL, content.Title), State = Types.FlashMessageState.Successful, CssClass = FlashMessageCssClasses.CONTENT_EDIT_SUCCESSFUL };
                return View("Edit", vm);
            }

            vm.Content.ClubAreas = _clubProvider.GetClubAreas();
            vm.Content.IsNew = false;
            vm.FlashMessage = new Types.FlashMessage { Message = string.Format(FlashMessages.CONTENT_EDIT_FAILED, content.Title), State = Types.FlashMessageState.Failed, CssClass = FlashMessageCssClasses.CONTENT_EDIT_FAILED };
            return View("Edit", vm);
        }

        public IActionResult Index(int clubAreaId)
        {
            var vm = new ContentViewModel();
            var canAdministerContent = _contentHandler.HasContentAdministratorRole();

            vm.PagedNews = _contentHandler.FetchContentForClubArea(clubAreaId, DateTime.MaxValue, !canAdministerContent, false);
            vm.ClubAreas = _contentHandler.GetClubAreas();
            vm.CurrentClubArea =  clubAreaId == 0 ? new Types.ClubArea { Id = 0, Description = "All Weston AC news", Name = "All news" }  : vm.ClubAreas.Find(x => x.Id == clubAreaId);
            vm.ClubAreaId = clubAreaId;
            vm.OldestNewsDateTime = vm.PagedNews.Count > 0 ? vm.PagedNews.OrderBy(x => x.PublishDateTime).FirstOrDefault().PublishDateTime : DateTime.Now;
            vm.CanAdministerContent = canAdministerContent;
            
            return View(vm);
        }
    }
}

wac/Controllers/SocialDiaryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using wac.Interfaces.Handlers.Events;
using wac.Interfaces.Providers;
using wac.Models.Events;
using wac.Types;
using wac.Types.Constants;

namespace wac.Controllers
{
    public class SocialDiaryController : Controller
    {
        private readonly ISocialDiaryHandler _socialDiaryHandler;
        private readonly IDateTimeProvider _dateTimeProvider;

        public SocialDiaryController(ISocialDiaryHandler socialDiaryHandler, IDateTimeProvider dateTimeProvider)
        {
            _socialDiaryHandler = socialDiaryHandler;
            _dateTimeProvider = dateTimeProvider;
        }

        public IActionResult Index()
        {
            var vm = new SocialDiaryViewModel();
            vm.CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole();
            vm.SocialEvents = _socialDiaryHandler.FetchSocialDiaryForClubArea(1, false);

            return View(vm);
        }

        public IActionResult View(int id)
        {
            var vm = new SocialEventViewModel();
            vm.CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole();
            vm.SocialEvent = _socialDiaryHandler.GetSocialEvent(id);

            return View(vm);
        }

        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        public IActionResult Create()
        {
            var vm = new SocialEventViewModel();
            vm.CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole();
            vm.SocialEvent = new SocialEvent { EventDate = _dateTimeProvider.GetUtcNow(), IsNew = true };

            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles = Roles.SOCIAL_DIARY_ADMINISTRATOR)]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SocialEvent socialEvent)
        {
            var vm = new SocialEventViewModel();
            vm.CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole();
            vm.SocialEvent = _socialDiaryHandler.CreateSocialEvent(socialEvent);
            vm.FlashMessage = new FlashMessage { Message = string.Format(FlashMessages.SOCIALDIARY_SAVE_SUCCESSFUL), State = FlashMessageState.Successful, CssClass = FlashMessageCssClasses.SOCIALDIARY_SAVE_SUCCESSFUL };

            return View("Edit", vm);
        }

        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        public IActionResult Edit(int id)
        {
            var vm = new SocialEventViewModel
            {
                CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole(),
                SocialEvent = _socialDiaryHandler.GetSocialEvent(id)
            };

            vm.SocialEvent.IsNew = false;

            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles = Roles.SOCIAL_DIARY_ADMINISTRATOR)]
        [ValidateAntiForgeryToken]
        public IActionResult Save(SocialEvent socialEvent)
        {
            var vm = new SocialEventViewModel
            {
                SocialEvent = socialEvent,
                CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole(),
            };

            vm.SocialEvent.ClubArea = new ClubArea { Id = 1 };

            if (_socialDiaryHandler.UpdateSocialEvent(socialEvent))
            {
                vm.SocialEvent.IsNew = false;
                vm.FlashMessage = new FlashMessage { Message = string.Format(FlashMessages.SOCIALDIARY_SAVE_SUCCESSFUL), State = FlashMessageState.Successful, CssClass = FlashMessageCssClasses.SOCIALDIARY_SAVE_SUCCESSFUL };
                return View("Edit", vm);
            }

            vm.SocialEvent.IsNew = false;
            vm.FlashMessage = new FlashMessage { Message = string.Format(FlashMessages.SOCIALDIARY_SAVE_FAILED), State = FlashMessageState.Failed, CssClass = FlashMessageCssClasses.SOCIALDIARY_SAVE_FAILED };
            return View("Edit", vm);
        }

        [HttpPost]
        [Authorize(Roles = Roles.SOCIAL_DIARY_ADMINISTRATOR)]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteEvent(SocialEventViewModel socialEventVm)
        {
            _socialDiaryHandler.DeleteEvent(socialEventVm.SocialEvent.Id);

            var vm = new SocialDiaryViewModel();
            vm.CanAdministerSocialDiary = _socialDiaryHandler.HasSocialDiaryAdministratorRole();
            vm.SocialEvents = _socialDiaryHandler.FetchSocialDiaryForClubArea(1, false);

            return View("Index", vm);
        }
    }
}

wac/Controllers/TrainingDiaryController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using wac.Interfaces.Handlers.Events;
using wac.Interfaces.Providers;
using wac.Models.Events;
using wac.Types.Constants;

namespace wac.Controllers
{
    [Authorize(Roles = Roles.TRAINING_DIARY_ADMINISTRATOR)]
    public class TrainingDiaryController : Controller
    {
        private readonly ITrainingDiaryHandler _trainingDiaryHandler;
        private readonly IClubProvider _clubProvider;
        private readonly ILogProvider _logProvider;
        private readonly IDateTimeProvider _dateTimeProvider;

        public TrainingDiaryController(ITrainingDiaryHandler trainingDiaryHandler, IClubProvider clubProvider, ILogProvider logProvider, IDateTimeProvider dateTimeProvider)
        {
            _trainingDiaryHandler = trainingDiaryHandler;
            _clubProvider = clubProvider;
            _logProvider = logProvider;
            _dateTimeProvider = dateTimeProvider;
        }

        public IActionResult Index(int clubAreaId)
        {
            var vm = new TrainingDiaryViewModel();
            var weekCommencing = _dateTimeProvider.CalculateWeekCommencing(DateTime.Now, DayOfWeek.Monday);

            vm.ClubAreas = _trainingDiaryHandler.GetClubAreas();
            vm.CurrentClubArea = clubAreaId == 0 ? new Types.ClubArea { Id = 1, Description = "Main", Name = "Main" } : vm.ClubAreas.Find(x => x.Id == clubAreaId);
            vm.events = _trainingDiaryHandler.FetchTrainingDiary(weekCommencing);
            vm.WeekCommencing = weekCommencing;

            return View(vm);
        }

        public IActionResult NextWeek(int clubAreaId, string weekCommencing)
        {
            var vm = new TrainingDiaryViewModel();
            var nextWeekCommencing = new DateTime();
            if (DateTime.TryParseExact(weekCommencing, Constants.CLIENTSIDE_DATETIME_FORMAT, CultureInfo.InvariantCulture, DateTimeStyles.AdjustToUniversal, out nextWeekCommencing))
            {
                nextWeekCommencing = nextWeekCommencing.AddDays(7);
                vm.ClubAreas = _trainingDiaryHandler.GetClubAreas();
                vm.CurrentClubArea = clubAreaId == 0 ? new Types.ClubArea { Id = 1, Description = "Main", Name = "Main" } : vm.ClubAreas.Find(x => x.Id == clubAreaId);
                vm.events = _trainingDiaryHandler.FetchTrainingDiary(nextWeekCommencing);
                vm.WeekCommencing = nextWeekCommencing;

                return View("Index", vm);
            }
            else {
                return null;
            }
        }

        public IActionResult PreviousWeek(int clubAreaId, string weekCommencing)
        {
            var vm = new TrainingDiaryViewModel();
            var previousWeekCommencing = new DateTime();
            if (DateTime.TryParseExact(weekCommencing, Constants.CLIENTSIDE_DATETIME_FORMAT, CultureInfo.InvariantCulture, DateTimeStyles.AdjustToUniversal, out previousWeekCommencing))
            {
                previousWeekCommencing = previousWeekCommencing.AddDays(-7);
                vm.ClubAreas = _trainingDiaryHandler.GetClubAreas();
                vm.CurrentClubArea = clubAreaId == 0 ? new Types.ClubArea { Id = 1, Description = "Main", Name = "Main" } : vm.ClubAreas.Find(x => x.Id == clubAreaId);
                vm.events = _trainingDiaryHandler.FetchTrainingDiary(previousWeekCommencing);
                vm.WeekCommencing = previousWeekCommencing;

                return View("Index", vm);
            }
            else
            {
                return null;
            }
        }

        public IActionResult Edit(int id)
        {
            throw new NotImplementedException();
        }

        [HttpGet]
        public IActionResult Create()
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Types.Event trainingDiaryEvent)
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save([FromBody]List<Types.Event> diaryEvents)
        {
            //var vm = new TrainingDiaryViewModel();
            //vm.CurrentClubArea = new Types.ClubArea { Name = "TEST" };

            //List<Types.Event> events = _trainingDiaryHandler.Save(diaryEvents);

            //if (events.Count > 0)
            //{
            //    vm.events = events;
            //    vm.FlashMessage = new Types.FlashMessage { Message = FlashMessages.TRAININGDIARY_SAVE_SUCCESSFUL, State = Types.FlashMessageState.Successful, CssClass = FlashMessageCssClasses.TRAININGDIARY_SAVE_SUCCESSFUL };
            //    return View(vm);
            //}
            //else
            //{
            //    vm.events = events;
            //    vm.FlashMessage = new Types.FlashMessage { Message = FlashMessages.TRAININGDIARY_SAVE_FAILED, State = Types.FlashMessageState.Failed, CssClass = FlashMessageCssClasses.TRAININGDIARY_SAVE_FAILED };
            //    return View(vm);
            //}

            throw new NotImplementedException();
        }


    }
}

wac/Controllers/UploadController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using wac.Interfaces.Handlers.Upload;
using wac.Models.Upload;
using wac.Types.Constants;

namespace wac.Controllers
{
    public class UploadController : Controller
    {
        private readonly IUploadHander _uploadHandler;

        public UploadController(IUploadHander uploadHandler)
        {
            _uploadHandler = uploadHandler;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        public IActionResult List()
        {
            var vm = new ListUploadsViewModel {
                Uploads = _uploadHandler.GetUploads()
            };
            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles = Roles.CONTENT_ADMINISTRATOR)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadFiles(IFormFile file)
        {
            await _uploadHandler.Upload(file);
            return RedirectToAction("Index");
        }
    }
}

wac/Views/Partials/_SocialDiary.cshtml
@model wac.Models.Events.SocialDiaryViewModel

    <aside>
        <div class="content">
            <h4><a asp-controller="SocialDiary" asp-action="Index" class="a-h4-link">Social Events</a></h4>
            <ul>
                @if (Model.SocialEvents.Count == 0)
                {
                    <li>
                        No social events are currently planned.
                    </li>
                }
                else
                {
                    foreach (var e in Model.SocialEvents)
                    {
                        <li>
                            <a asp-controller="SocialDiary" asp-action="View" asp-route-id="@e.Id">@e.Title</a> @e.EventDate.ToString("dddd, d MMMM yyyy") at @e.EventTime.ToString("HH:mm")
                        </li>
                    }
                }
            </ul>
        </div>
    </aside>

wac/Views/Partials/_TrainingDiary.cshtml
@model wac.Models.Events.TrainingDiaryViewModel
<section class="training-diary">
    <article>
        <h2>Training diary</h2>
        <h3>Week commencing: @Model.WeekCommencing.ToString("dddd, d MMMM yyyy")</h3>
        @if (Model.events.Count > 0)
        {
            <div class="container">
                @foreach (var e in Model.events)
                {
                    if (!string.IsNullOrEmpty(e.Location) || !string.IsNullOrEmpty(e.Description))
                    {
                        <div class="row">
                            <div class="col-xs-1">@e.EventDate.ToString("dddd"):</div>
                            @if (string.IsNullOrEmpty(e.Location))
                            {
                                <div class="col-xs-10">@e.Description</div>
                            }
                            else
                            {
                                <div class="col-xs-10">@e.Location (@e.Description)</div>
                            }
                        </div>
                    }
                }
            </div>
        }
        else
        {
            <div>There are no events in the training diary for this week</div>
        }
        @if (Model.CanAdministerTrainingDiary)
        {
            <div class="margin-top-10"><a asp-controller="TrainingDiary" asp-action="Index">Edit training diary</a></div>
        }
    </article>
</section>

wac/Views/Partials/_contentEditorCreator.cshtml
@model wac.Types.Content
<form asp-controller="Content" asp-action="@(Model.IsNew ? "create" : "save")" method="post" onsubmit="return validateAndBind(Event)">
    <div class="form-group float-left padding-right-20">
        <label asp-for="Title">Title</label> <input asp-for="Title" />
    </div>
    <div class="form-group">
        <label asp-for="PublishDateTimeText">Publish Date</label> <input class="datepicker" asp-for="PublishDateTimeText" />
    </div>
    <div class="float-left"><label asp-for="ClubAreas">Club area</label></div>
    <div class="float-left padding-right-10">
        @Html.DropDownListFor(m => m.ClubArea.Id, new SelectList(Model.ClubAreas, "Id", "Name"), "Select club area...")
    </div>
    <div class="form-check float-left padding-right-20">
        <label asp-for="Featured">Featured</label><input asp-for="Featured" />
    </div>
    <div class="form-check">
        <label asp-for="Active">Is Active</label> <input asp-for="Active" />
    </div>
    <div class="form-group">
        <label asp-for="Body">Content</label> <textarea asp-for="Body" rows="10"></textarea>
        <a class="font-size-small" href="http://agea.github.io/tutorial.md/" target="_blank">How to use markdown</a>
    </div>
    <input asp-for="@Model.Id" value="@this.Model.Id" type="hidden" />
    <input type="hidden" asp-for="@Model.ClubArea.Id" />
    <input type="hidden" asp-for="@Model.PublishDateTime" />
    <input asp-for="ClubArea.Id" type="hidden" />
    <input type="submit" value="Save" />
</form>
<br />
@await Html.PartialAsync("~/Views/Partials/_uploadFile.cshtml")

wac/Views/Partials/_cookieConsentPartialView.cshtml
@using Microsoft.AspNetCore.Http.Features

@{
    var consentFeature = Context.Features.Get<ITrackingConsentFeature>();
    var showBanner = !consentFeature?.CanTrack ?? false;
    var cookieString = consentFeature?.CreateConsentCookie();
}

@if (showBanner)
{
    <nav id="cookieConsent" class="navbar navbar-default navbar-fixed-top" role="alert">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#cookieConsent .navbar-collapse">
                    <span class="sr-only">Toggle cookie consent banner</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse">
                <p class="navbar-text">
                    By using our site, you agree to our use of <a asp-action="Cookies">cookies</a>.
                </p>
                <div class="navbar-right">
                    <a asp-action="Privacy" class="btn btn-info navbar-btn">Privacy</a>
                    <a asp-action="DataProtection" class="btn btn-info navbar-btn">Data protection</a>
                    <button type="button" class="btn btn-default navbar-btn" data-cookie-string="@cookieString">Accept</button>
                </div>
            </div>
        </div>
    </nav>
    <script>
        (function () {
            document.querySelector("#cookieConsent button[data-cookie-string]").addEventListener("click", function (el) {
                document.cookie = el.target.dataset.cookieString;
                document.querySelector("#cookieConsent").classList.add("hidden");
            }, false);
        })();
    </script>
}

wac/Views/Partials/_newsGrid.cshtml
@model IEnumerable<wac.Models.Content.NewsGridViewModel>

wac/Views/Partials/_socialEventEditorCreator.cshtml
@model wac.Types.SocialEvent
<form asp-controller="SocialDiary" asp-action="@(Model.IsNew ? "create" : "save")" method="post" onsubmit="return validateAndBind(Event)">
    <div class="container">
        <div class="row">
            <div class="col-lg-10"><label asp-for="Title">Title</label> <input asp-for="Title" size="100" maxlength="45" /></div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group float-left margin-right_20">
                    <label asp-for="EventDate">Date</label> <input class="datepicker" asp-for="EventDateText" size="25" />
                </div>
                <div class="form-group">
                    <label asp-for="EventTime">Time</label> <input asp-for="EventTime" placeholder="00:00" type="time" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <label asp-for="Description">Description</label> <textarea asp-for="Description" rows="10"></textarea>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-1">
                <label asp-for="Location">Location</label>
            </div>
            <div class="col-lg-4">
                <input asp-for="Location" size="50" maxlength="45" />
            </div>
            <div class="col-lg-1">
                <label asp-for="Organiser">Organiser</label>
            </div>
            <div class="col-lg-4">
                <input asp-for="Organiser" size="50"  maxlength="255"/>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-1">
                <label asp-for="Email">Email</label>
            </div>
            <div class="col-lg-4">
                <input asp-for="Email" size="50" maxlength="255" />
            </div>
            <div class="col-lg-1">
                <label asp-for="Facebook">Facebook</label>
            </div>
            <div class="col-lg-4">
                <input asp-for="Facebook" size="50" maxlength="255" />
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-lg-12">
                <input type="submit" value="Save" />
            </div>
        </div>
    </div>
    <input asp-for="@Model.Id" value="@this.Model.Id" type="hidden" />
    <input type="hidden" asp-for="@Model.EventDate" />

</form>

wac/Views/Partials/_uploadFile.cshtml
<div class="">
    <div class="dropzone-container" id="dropzone">
        <form action="/Upload/UploadFiles" id="uploader" class="dropzone-container dropzone">
            <div id="dropzone-drop-area" class="dropzone-drop-area">
            </div>
            @Html.AntiForgeryToken()
        </form>
    </div>
</div>
<a asp-controller="Upload" asp-action="List" class="font-size-small" >View all uploaded content</a>
<link rel="stylesheet" href="~/css/dropzone.css" />

<script src="~/js/dropzone.js"></script>
<script src="~/js/dropzone.options.js"></script>